[package]
name = "hist"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
regex = "1.5"
execute = "0.2.11"
ansi_term = "0.12.1"
anyhow = "1.0.57"
